### ISSUE TITLE
垂直居中的问题

### ISSUE THREAD

**Issue by Panici4** [ltadpoles/web-document#32]
`如何让一个不定宽高的盒子水平垂直居中，使用定位的方法。

.father {
    position: relative;
}
.son {
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    margin: auto;
}`
并不能让不定宽高的盒子.son居中，只会使.son的宽高和父亲一样把。
貌似只有.son加上宽高这个方法才可以实现水平垂直居中。

**Comment by ltadpoles** [comment]
感谢指出 已修改
